sudo: false

language: scala

scala:
  - 2.11.8

jdk:
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test it:test

cache:
  directories:
    - '$HOME/.ivy2/cache'

notifications:
  email:
    - christopher.townson@digital.hmrc.gov.uk

